// src/components/indicator.jsx
import { h } from 'preact'
import Indicator from 'components/layout/box-indicator'

const regionName = (data) => data.region ? data.region.name : '-'
const members = (data) => data.memberCount ? data.memberCount : '0'
const donations = (data) => data.donations ? data.donations : '0'
const trophies = (data) => data.score ? data.score : '0'

const Indicators = ({ clan }) => (
    <div style="margin: 20px;">
        <br/>
        <div class="columns">
            <Indicator value={members(clan)}>
                Membros
            </Indicator>
            <Indicator value={trophies(clan)}>
                Trof&eacute;us
            </Indicator>
            <Indicator value={donations(clan)}>
                Doa&ccedil;&otilde;es
            </Indicator>
            <Indicator value={regionName(clan)}>
                Regi&atilde;o
            </Indicator>
            
        </div>
    </div>
)

export default Indicators

// src/components/indicator.vue
<template>
    <div style="margin: 20px;">
        <br/>
        <div class="columns">
            <Indicator :value="members()">Membros</Indicator>
            <Indicator :value="trophies()">Trof&eacute;us</Indicator>
            <Indicator :value="donations()">Doa&ccedil;&otilde;es</Indicator>
            <Indicator :value="regionName()">Regi&atilde;o</Indicator>
        </div>
    </div>
</template>

<script>
import Indicator from 'components/layout/box-indicator'

const Indicators = {
    name: 'indicators',

    props: [ 'clan' ],

    components: { Indicator },

    methods: {
        regionName() { return this.clan.region ? this.clan.region.name : '-' },
        members() { return this.clan.memberCount ? this.clan.memberCount : '0' },
        donations() { return this.clan.donations ? this.clan.donations : '0' },
        trophies() { return this.clan.score ? this.clan.score : '0' }
    }
}

export default Indicators
</script>
