// src/components/members.jsx
import { h } from 'preact'
import MemberCard from 'components/member-card'

const MemberList = ({ clan }) => (
    <div class="box" style="margin: 20px;">
        <div class="columns is-multiline">
            {clan.members ? clan.members.map(member => <MemberCard key={member.tag} data={member} />) : null}
        </div>
    </div>
)

export default MemberList

// src/components/members.vue
<template>
    <div class="box" style="margin: 20px;">
        <div class="columns is-multiline">
            <MemberCard v-for="data in list" :key="data.tag" :member="data"></MemberCard>
        </div>
    </div>
</template>
<script>
    import MemberCard from 'components/member-card'

    export default {
        name: 'member-list',

        props: [ 'list' ],

        components: { MemberCard }
    }
</script>
