// src/components/topnav.vue
<template>
    <nav id="topbar" class="navbar topbar_nav">
        <div class="navbar-brand topnav-left">
            <div class="navbar-item">
                <span class="icon"><img :src="data.brand" border="0" /></span> 
                <span>&nbsp;<b>{{data.name}}</b> ({{data.description}})</span>
            </div>
        </div>
        <div class="navbar-menu">
            <div class="navbar-start">
            </div>
            <div class="navbar-end">
                <span class="navbar-item">
                    Tag: {{tag}}
                </span>
            </div>
        </div>
    </nav>
</template>

<script>
    const TopNav = {
        name: 'topnav',

        props: [ 'data' ],

        data: () => ({
            tag: '2YQ8UQC'
        })
    }

    export default TopNav
</script>

// src/components/topnav.jsx
import { h } from 'preact'

const TopNav = ({ data }) => (
    <nav id="topbar" class="navbar topbar_nav">
        <div class="navbar-brand topnav-left">
            <div class="navbar-item">
                <span class="icon"><img src={data.brand} border="0" /></span> 
                <span>&nbsp;{data.name} ({data.description})</span>
            </div>
        </div>
        <div class="navbar-menu">
            <div class="navbar-start">
            </div>
            <div class="navbar-end">
                <span class="navbar-item">
                    Tag: 2YQ8UQC
                </span>
            </div>
        </div>
    </nav>
)

export default TopNav
